require('plugins.config.lsp.lua_lsp')
require('plugins.config.lsp.golang')
require('plugins.config.lsp.typescript')
require('plugins.config.lsp.godot')
require('plugins.config.lsp.tailwind')
-- require('config.lsp.yaml')
-- require('config.lsp.vim')
-- require('config.lsp.json')
-- require('config.lsp.python')
