require('plugins.config.lsp.installer_config.lua_lsp')
require('plugins.config.lsp.installer_config.golang')
require('plugins.config.lsp.installer_config.json')
require('plugins.config.lsp.installer_config.rust')
require('plugins.config.lsp.installer_config.typescript')
